### ISSUE TITLE
Show entire tree when started

### ISSUE THREAD

**Issue by timofurrer** [whitewhidow/gource-live#9]
Would it be possible to show the entire tree upon start? Instead of just the leaves containing the current changes? 
If I have a huge tree it takes a while to recreate it with `gource-live.sh -s ...` which is a pain when restarting gource or the machine ..

**Comment by whitewhidow** [comment]
i'll look into it in tho coming days

**Comment by whitewhidow** [comment]
im a bit slow these days,   havent forgotten tho !!

**Comment by SimplyLinn** [comment]
For a list of all files in the work-tree of a commit using git, there's this command.
`git ls-tree --name-only -r <REVISION-ISH>`
Using AWK to format this into gource custom log format, with "init" as user and a timestamp of 0
`git ls-tree --name-only -r <REVISION-ISH> | awk '{print "0|init|A|"$0}'`

I've not looked into the other version controls yet, and I'm a bit to busy to create a pull-request right now. I may do it in the coming weeks or so though, if it's not done by then.

(I also need this functionality for an enormous project with over 20k commits)
